check-for-updates: true
messages:
  - playerMOTD
  - staffMOTD
enable-first-time-message: false
first-time-message:
  - "&d&lWelcome to the Server, &a%PLAYER%&d!"
playerMOTD:
  - "&5============================="
  - "&f - &6Remember to Be Respectful to All Players."
  - "&f - &6Remember to Read the &e/rules&6!"
  - "&5============================="

staffMOTD:
  - "&5============================="
  - "&f - &6Big Changes Coming Next Month!"
  - "&f - &6Make sure to consult the punishment guide, do &e/punguide&6!"
  - "&5============================="